version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mng
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - ./products.json:/products.json
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mnge
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

volumes:
  mongo-data:
